import { expect, test } from '@playwright/test'

test.describe('J02 planned market journey', () => {
	test.use({ viewport: { width: 390, height: 900 }, colorScheme: 'dark', timezoneId: 'UTC', locale: 'zh-CN' })
	test('J02.state.01 anonymous ready zh-CN mobile390 dark UTC', async ({ page, context }, testInfo) => {
		test.skip(Boolean(process.env.PLAYWRIGHT_BASE_URL), 'Only the isolated fixture supports this planned scenario')
		await page.addInitScript(() => localStorage.setItem('theme', 'dark'))
		expect((await context.cookies()).filter(cookie => /session/i.test(cookie.name))).toHaveLength(0)
		const historyRequests: number[] = []
		await page.route('**/api/graphql', async route => {
			const body = route.request().postDataJSON()
			if (!body?.query?.includes('query GetPlayerValueHistory(')) return route.continue()
			const playerId = Number(body.variables.playerId)
			historyRequests.push(playerId)
			await route.fulfill({ json: { data: { playerValueHistory: [{ playerId, changeDate: '2026-08-03', oldValue: 99, newValue: 100, changeType: 'RISE', transfersIn: null, transfersOut: null }] } } })
		})
		await page.goto('/zh-CN')
		await expect(page.locator('html')).toHaveClass(/dark/)
		expect(await page.evaluate(() => Intl.DateTimeFormat().resolvedOptions().timeZone)).toBe('UTC')
		const homeMarket = page.locator('[data-home-carousel="home-market"]')
		await expect(homeMarket).toContainText('Saka')
		const marketLink = homeMarket.locator('a[href="/zh-CN/explore/market"]:visible')
		await expect(marketLink).toHaveCount(1)
		await marketLink.click()
		await expect(page).toHaveURL(/\/zh-CN\/explore\/market$/)
		await expect(page.locator('#market-most-selected-share li')).toHaveCount(4)
		const periods = page.getByRole('navigation', { name: '持有率比较周期', exact: true })
		await periods.getByRole('link', { name: 'GW 比较', exact: true }).click()
		await expect(page).toHaveURL(/period=GAMEWEEK/)
		await expect(periods.getByRole('link', { name: 'GW 比较', exact: true })).toHaveAttribute('aria-current', 'page')
		await expect(page.locator('#market-ownership-share')).toContainText('GW2')
		await periods.getByRole('link', { name: '每日', exact: true }).click()
		await expect(page).toHaveURL(/period=DAILY/)
		const historicalDate = page.getByRole('navigation', { name: '每日快照日期', exact: true }).locator('a[href*="date=2026-08-02"]')
		await expect(historicalDate).toHaveCount(1)
		await historicalDate.click()
		await expect(page).toHaveURL(/period=DAILY&date=2026-08-02/)
		await expect(historicalDate).toHaveAttribute('aria-current', 'date')
		await expect(page.locator('#market-ownership-share')).toContainText('Saka')
		const marketUrl = page.url()
		await page.getByRole('searchbox', { name: '按姓名搜索球员', exact: true }).fill('Sa')
		const saka = page.getByRole('list', { name: '球员搜索结果', exact: true }).getByRole('listitem').filter({ has: page.getByRole('link', { name: 'Saka', exact: true }) })
		await expect(saka).toHaveCount(1)
		await saka.getByRole('button', { name: '历史', exact: true }).click()
		await expect(page.getByRole('heading', { level: 3, name: 'Saka', exact: true })).toBeVisible()
		await expect(page.getByRole('list', { name: 'Saka 的身价历史', exact: true })).toContainText('£9.9m → £10.0m')
		await page.getByRole('button', { name: '选择其他球员', exact: true }).click()
		await page.getByRole('searchbox', { name: '按姓名搜索球员', exact: true }).fill('Sa')
		await saka.getByRole('link', { name: 'Saka', exact: true }).click()
		await expect(page).toHaveURL(/\/zh-CN\/explore\/player-stats\?p1=1$/)
		await expect(page.getByRole('region', { name: '球员总览', exact: true })).toContainText('Saka')
		await page.locator('button[aria-controls="ps-context-panel"]').click()
		await expect(page.locator('#ps-market-section')).toContainText('£10.0m')
		await expect(page.locator('#ps-market-section [aria-busy="true"]')).toHaveCount(0)
		expect(historyRequests).toEqual([1])
		await page.goBack()
		await expect(page).toHaveURL(marketUrl)
		await expect(page.getByRole('navigation', { name: '每日快照日期', exact: true }).locator('[aria-current="date"]')).toHaveAttribute('href', /date=2026-08-02/)
		await expect(page.locator('#market-ownership-share')).toContainText('Saka')
		await testInfo.attach('J02.state.01-binding', { contentType: 'application/json', body: JSON.stringify({ variantId: 'J02.state.01', persona: 'A', locale: 'zh-CN', viewport: { width: 390, height: 900 }, theme: 'dark', timezone: 'UTC', scenario: 'ready', historicalDate: '2026-08-02', playerId: 1, returnedUrl: marketUrl, readyMs: null, performanceStatus: 'NOT_RUN', raceCoverage: 'Separate MKT02 controlled race tests; not inferred from this ready journey' }) })
	})
})
